name: Deploy and Test on Kong

on:
  push:
    branches: 
      - master
      
jobs:
  call-workflow:
    uses: ./.github/workflows/actions_push_pr.yml
      
  deploy_to_kong:
    runs-on: self-hosted
    name: Deploy
    needs: call-workflow
    steps:        
    - name: Deploy declarative config
      run: |
        /bin/sh -c 'pushd /tmp && deck sync --kong-addr http://admin.kong.demo:8001 --headers Kong-Admin-Token:kong'
  test_kong:
    runs-on: self-hosted
    name: Integration Testing
    needs: deploy_to_kong
    steps:        
    - name: Run Unit Tests
      run: |
        /bin/sh -c 'inso run test uts_616d31 -e env_env_3abee4'
  publish_to_portal:
    runs-on: self-hosted
    name: Publish
    needs: test_kong
    steps:            
    - name: Publish Spec to Dev Portal
      run: |
        /bin/sh -c 'pushd ./specs && http --check-status --ignore-stdin PUT http://admin.kong.demo:8001/default/files/specs/orders.yaml Kong-Admin-Token:kong contents=@orders.yaml'
