name: Build and Test Kong Config
on: 
  workflow_call:
  pull_request:
    branches: 
      - main
jobs:
  build_kong_config:
    runs-on: self-hosted
    name: Build Config
    steps:        
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint OpenAPI Spec
      run: |
        /bin/sh -c 'inso lint spec ./specs/orders.yaml'
    - name: Generate Kong declarative configuration from Spec
      run: |
        /bin/sh -c 'inso generate config ./specs/orders.yaml --type declarative > /tmp/kong.yaml'
  static_code_analysis:
    runs-on: self-hosted
    name: Static Code Analysis
    needs: build_kong_config
    steps:        
    - name: Validate Kong declarative configuration
      run: |
        /bin/sh -c 'pushd /tmp && deck validate'
